DROP DATABASE IF EXISTS `Bibloteka`;
CREATE DATABASE `Bibloteka`;
USE `Bibloteka`;

CREATE TABLE `Ksiazka`(
`Imie` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`NazwiskoAutora`VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`ISBN ` INT(20)NOT NULL,
`Tytul`VARCHAR(50) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL ,
PRIMARY KEY(`ISBN `))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

CREATE TABLE `Czytelnik`(
`Imie` VARCHAR(20) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Nazwisko`VARCHAR(40) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`DataUrodzenia ` Date NOT NULL,
`Pesel` INT (20) NOT NULL ,
PRIMARY KEY(`Pesel`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;


CREATE TABLE `OddzialBibloteki`(
`Id_oddzial` int(10) NOT NULL AUTO_INCREMENT,
`Nazwa`VARCHAR(80) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
`Adres` VARCHAR(80) CHARACTER SET utf8 COLLATE utf8_polish_ci NOT NULL,
PRIMARY KEY(`Id_oddzial`))
DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1;

